class Traducciones {
  static final Map<String, Map<String, String>> _localizedStrings = {
    "es": {
      "Send": "Enviar",
      "Receive": "Recibir",
      "Profile": "Perfil",
      "Select user type": "Por favor selecciona el tipo de usuario",
      "Successfully registered": "Registrado exitosamente",
      "Error registering user": "Error al registrar al usuario",
      "Database error": "Error en la base de datos",
      "Error": "Error",
      "Accept": "Aceptar",
      "Register": "Registro",
      "Name:": "Nombre:",
      "Name": "Nombre",
      "Please enter your name": "Por favor ingresa tu nombre",
      "Last name": "Apellidos",
      "Please enter your last name": "Por favor ingresa tus apellidos",
      "Email": "Correo",
      "Please enter your email": "Por favor ingresa tu correo",
      "Please enter a valid email": "Por favor ingresa un correo válido",
      "Password": "Contraseña",
      "Please enter a password": "Por favor ingresa una contraseña",
      "Password must be at least 6 characters":
          "La contraseña debe tener al menos 6 caracteres",
      "Confirm Password": "Confirmar Contraseña",
      "Please confirm your password": "Por favor confirma tu contraseña",
      "User Type": "Tipo de usuario",
      "You have no received emails.": "No tienes correos recibidos",
      "Student": "Alumno",
      "Teacher": "Profesor",
      "Next": "Siguiente",
      "Delete": "Eliminar",
      "Email count": "Recuento correos",
      "Total sent emails:": "Total de correos enviados:",
      "Sent emails": "Correos enviados",
      "Inbox": "Bandeja de Entrada",
      "Filter:": "Filtro",
      "Filter Teacher": "Filtro Profesor",
      "Filter Student": "Filtro Alumno",
      "No received emails": "No tienes correos recibidos",
      "Received emails": "Correos recibidos",
      "From:": "De:",
      "Subject:": "Asunto:",
      "Body:": "Cuerpo",
      "Subject": "Asunto",
      "No sender": "Sin remitente",
      "No subject": "Sin asunto",
      "No body": "Sin cuerpo",
      "Delete email": "Eliminar correo",
      "Delete user": "Eliminar usuario",
      "¿Confirm delete email?":
          "¿Estás seguro de que deseas eliminar este correo?",
      "Cancel": "Cancelar",
      "Enter your email": "Ingresa tu correo",
      "Enter your password": "Ingresa tu contraseña",
      "Please enter your password": "Por favor, ingresa tu contraseña",
      "Login": "Ingresar",
      "Create Account": "Crear Cuenta",
      "Write Email": "Escribir Correo",
      "To (Email)": "Para (Email)",
      "Please enter recipient email":
          "Por favor ingresa el correo del destinatario",
      "Please enter a subject": "Por favor ingresa un asunto",
      "Message": "Mensaje",
      "Please enter a message": "Por favor ingresa un mensaje",
      "Success": "Éxito",
      "Email sent successfully": "Correo enviado correctamente",
      "Error sending email:": "Error al enviar el correo:",
      "My Sent Emails": "Mis Correos Enviados",
      "No sent emails": "No hay correos enviados",
      "Change language": "Cambiar idioma",
      "Night mode": "Modo nocturno",
      "Log out": "Cerrar sesion",
      "Change password": "Cambiar contraseña",
      "Profile Student": "Perfil Alumno",
      "Are you sure you want to delete your account? This action cannot be undone.":
          "¿Estás seguro de que deseas eliminar tu cuenta? Esta acción no se puede deshacer.",
      "User deleted successfully.": "Usuario eliminado correctamente",
      "User not found in session.": "No se encontró el usuario en sesión",
      "¿Are you sure you want to log out?":
          "¿Estás seguro de que deseas cerrar sesión?",
      "Password changed successfully.": "Contraseña cambiada con exito.",
      "Error: User not found in session.":
          "Error: No se encontró el usuario en sesión.",
      "New password": "Nueva contraseña",
      "The password cannot be empty.": "La contraseña no puede estar vacia.",
      "It must be at least 6 characters long":
          "Debe tener al menos 6 caracteres",
      "Save": "Guardar",
      "Delete Account": "Eliminar cuenta",
      "The password cannot be empty": "La contraseña no puede estar vacía",
      "Total received emails:": "Total correos recibidos:",
      'Preview Email': 'Previsualizar Correo',
      'Dialog Box': 'Cuadro de diálogo',
      'Show dialog box?': '¿Mostrar cuadro de diálogo?',
      'The user does not exist or the password is incorrect.':
          'El usuario no existe o la contraseña es incorrecta.',
      'Login button': 'Botón de ingresar a la app',
      'Press when you have entered your username and password':
          'Pulse cuando termine de ingresar usuario y contraseña',
      'Create account button': 'Botón de crear cuenta',
      'Press to create a new account': 'Pulse para crear una cuenta nueva',
      'Passwords do not match': 'Las contraseñas no coinciden',
      'Please select user type': 'Por favor selecciona el tipo de usuario',
      'User registered successfully': 'Usuario registrado exitosamente',
      'Database error: ': 'Error en la base de datos: ',
      'Clear': 'Borrar',
      "Close": "Cerrar",
      "The recipient does not exist":"El destinatario no existe",
      "The sender does not exist in the database":"El emisor no existe en la base de datos",
      "You are not logged in":"No se ha iniciado sesión",
      "Confirm new password":"Confirma la nueva contraseña",
      "Incorrect current password":"Contraseña actual incorrecta",
      "Fields cannot be empty":"Los campos no pueden estar vacíos",
    },
    "en": {
      "Send": "Send",
      "Receive": "Receive",
      "Profile": "Profile",
      "Select user type": "Please select the user type",
      "Successfully registered": "Successfully registered",
      "Error registering user": "Error registering user",
      "Database error": "Database error",
      "Error": "Error",
      "Accept": "Accept",
      "Register": "Register",
      "Name:": "Name:",
      "Name": "Name",
      "Please enter your name": "Please enter your name",
      "Last name": "Last name",
      "Please enter your last name": "Please enter your last name",
      "Email": "Email",
      "Please enter your email": "Please enter your email",
      "Please enter a valid email": "Please enter a valid email",
      "Password": "Password",
      "Please enter a password": "Please enter a password",
      "Password must be at least 6 characters":
          "Password must be at least 6 characters",
      "Confirm Password": "Confirm Password",
      "Please confirm your password": "Please confirm your password",
      "User type": "User type",
      "Student": "Student",
      "Teacher": "Teacher",
      "Next": "Next",
      "Delete": "Delete",
      "Email count": "Email count",
      "Total sent emails:": "Total sent emails:",
      "Total received emails:": "Total received emails:",
      "Sent emails": "Sent emails",
      "Inbox": "Inbox",
      "Filter": "Filter",
      "Filter Teacher": "Filter Teacher",
      "Filter Student": "Filter Student",
      "No received emails": "No received emails",
      "From:": "From:",
      "Subject:": "Subject:",
      "Body:": "Body:",
      "Subject": "Subject",
      "No sender": "No sender",
      "No subject": "No subject",
      "No body": "No body",
      "Delete email": "Delete email",
      "Confirm delete email": "Are you sure you want to delete this email?",
      "Cancel": "Cancel",
      "Enter your email": "Enter your email",
      "Enter your password": "Enter your password",
      "Please enter your password": "Please enter your password",
      "Login": "Login",
      "Create Account": "Create Account",
      "Write Email": "Write Email",
      "To (Email)": "To (Email)",
      "Please enter recipient email": "Please enter recipient email",
      "Please enter a subject": "Please enter a subject",
      "Message": "Message",
      "Please enter a message": "Please enter a message",
      "Success": "Success",
      "Email sent successfully": "Email sent successfully",
      "Error sending email:": "Error sending email:",
      "My Sent Emails": "My Sent Emails",
      "No sent emails": "No sent emails",
      "Change language": "Change language",
      "Night mode": "Night mode",
      "Log out": "Log out",
      "Change password": "Change password",
      "Delete user": "Delete user",
      "Received emails": "Received emails",
      "You have no received emails.": "You have no received emails.",
      "Profile Student": "Profile Student",
      "Are you sure you want to delete your account? This action cannot be undone.":
          "Are you sure you want to delete your account? This action cannot be undone.",
      "User deleted successfully.": "User deleted successfully.",
      "User not found in session.": "User not found in session.",
      "¿Are you sure you want to log out?":
          "¿Are you sure you want to log out?",
      "Password changed successfully.": "Password changed successfully.",
      "Error: User not found in session.": "Error: User not found in session.",
      "New Password": "New Password",
      "The password cannot be empty.": "The password cannot be empty.",
      "It must be at least 6 characters long":
          "It must be at least 6 characters long",
      "Save": "Save",
      "Delete Account": "Delete Account",
      "The password cannot be empty": "The password cannot be empty",
      'Preview Email': 'Preview Email',
      'Dialog Box': 'Dialog Box',
      'Show dialog box?': 'Show dialog box?',
      'The user does not exist or the password is incorrect.':
          'The user does not exist or the password is incorrect.',
      'Login button': 'Login button',
      'Press when you have entered your username and password':
          'Press when you have entered your username and password',
      'Create account button': 'Create account button',
      'Press to create a new account': 'Press to create a new account',
      'Passwords do not match': 'Passwords do not match',
      'Please select user type': 'Please select user type',
      'User registered successfully': 'User registered successfully',
      'Database error: ': 'Database error: ',
      'Clear': 'Clear',
      'Close': 'Close',
      "The recipient does not exist":"The recipient does not exist",
      "The sender does not exist in the database":"The sender does not exist in the database",
      "You are not logged in":"You are not logged in",
      "Confirm new password":"Confirm new password",
      "Incorrect current password":"Incorrect current password",
      "Fields cannot be empty":"Fields cannot be empty",
    }
  };

  static String translate(String languageCode, String key) {
    return _localizedStrings[languageCode]?[key] ?? key;
  }
}
